# Generated by Django 4.1.6 on 2023-03-04 17:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='reply_tos',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=75), size=50), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='email',
            name='recipients',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=75), size=50), size=50),
        ),
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.EmailField(max_length=75),
        ),
    ]
