# Generated by Django 4.1.6 on 2023-03-04 17:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_email_reply_tos_alter_email_recipients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='reply_tos',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=75), size=50), size=None),
        ),
    ]
