# Generated by Django 4.1.6 on 2023-03-25 16:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_alter_email_reply_tos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='reply_tos',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=75), size=50), null=True, size=50),
        ),
    ]
