# Generated by Django 4.1.6 on 2023-03-27 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_rename_email_organization_mailer_email'),
        ('mailer', '0004_alter_email_reply_tos'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
