# Generated by Django 4.2.6 on 2024-07-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_active_project_finished_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='finished_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
