# Generated by Django 4.2.6 on 2024-12-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_finished_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='documentation/')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='documentation',
            field=models.ManyToManyField(to='projects.documentation'),
        ),
    ]
