# Generated by Django 4.2.6 on 2024-12-10 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_documentation_project_documentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='documentation/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='documentation',
        ),
        migrations.DeleteModel(
            name='Documentation',
        ),
        migrations.AddField(
            model_name='projectdocumentation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentation', to='projects.project'),
        ),
    ]
