# Generated by Django 4.2.6 on 2024-12-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_contributors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocumentation',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
