# Generated by Django 4.2.6 on 2024-12-17 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectdocumentation_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdocumentation',
            old_name='description',
            new_name='doc_description',
        ),
    ]
