# Generated by Django 4.2.6 on 2024-12-17 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_description_projectdocumentation_doc_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdocumentation',
            old_name='doc_description',
            new_name='description',
        ),
    ]
