# Generated by Django 3.2.16 on 2023-01-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0008_auto_20230103_1613'),
        ('timesheets', '0012_alter_timesheetperiod_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_time', models.DateTimeField(auto_now_add=True)),
                ('approvee', models.ManyToManyField(related_name='approvee_approvals', to='employee.TimesheetUser')),
                ('approver', models.ManyToManyField(related_name='approver_approvals', to='employee.TimesheetUser')),
                ('timesheet_entry', models.ManyToManyField(related_name='approvals', to='timesheets.TimesheetEntry')),
            ],
        ),
    ]
