# Generated by Django 3.2.16 on 2023-01-03 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20230103_1613'),
        ('timesheets', '0012_alter_timesheetperiod_options'),
        ('tsmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='approvee',
        ),
        migrations.AddField(
            model_name='approval',
            name='approvee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvee_approvals', to='employee.timesheetuser'),
        ),
        migrations.RemoveField(
            model_name='approval',
            name='approver',
        ),
        migrations.AddField(
            model_name='approval',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver_approvals', to='employee.timesheetuser'),
        ),
        migrations.RemoveField(
            model_name='approval',
            name='timesheet_entry',
        ),
        migrations.AddField(
            model_name='approval',
            name='timesheet_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='timesheets.timesheetentry'),
        ),
    ]
