# Generated by Django 4.2.6 on 2024-07-16 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='acquired_date',
            new_name='date_acquired',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='retired_date',
            new_name='date_retired',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='mileage',
            new_name='total_mileage',
        ),
    ]
