# Generated by Django 4.2.6 on 2024-07-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_rename_acquired_date_asset_date_acquired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='date_retired',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
