# Generated by Django 4.2.6 on 2024-07-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_date_retired_alter_asset_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='year_built',
            field=models.IntegerField(),
        ),
    ]
