# Generated by Django 4.1.2 on 2022-10-31 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(blank=True)),
                ('emp_name', models.CharField(max_length=255)),
                ('date_time_in', models.CharField(max_length=255)),
                ('date_time_out', models.CharField(max_length=255)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
