# Generated by Django 2.1 on 2020-01-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=255)),
                ('date_time_in', models.DateTimeField()),
                ('date_time_out', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('salary', models.FloatField()),
            ],
        ),
    ]
