# Generated by Django 3.2.16 on 2022-11-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_timesheetuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetuser',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
