# Generated by Django 2.1 on 2020-01-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='salary',
            new_name='hourly_rate',
        ),
        migrations.AlterField(
            model_name='employee',
            name='duration',
            field=models.FloatField(),
        ),
    ]
