# Generated by Django 2.1 on 2020-01-12 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200111_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='user_id',
            field=models.IntegerField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
