# Generated by Django 3.2.16 on 2022-11-22 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_alter_organization_timezone'),
        ('employee', '0003_timesheetuser_hourly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetuser',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
