# Generated by Django 2.1 on 2020-01-12 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20200111_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='user_id',
            new_name='emp_id',
        ),
    ]
