# Generated by Django 3.2.16 on 2022-12-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20221230_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetuser',
            name='approvees',
            field=models.ManyToManyField(blank=True, related_name='approvee_set', to='employee.TimesheetUser'),
        ),
    ]
