# Generated by Django 2.1 on 2020-01-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20200111_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_time_in',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_time_out',
            field=models.CharField(max_length=255),
        ),
    ]
