# Generated by Django 3.2.16 on 2023-01-03 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_timesheetuser_approvees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetuser',
            name='is_approver',
        ),
    ]
