# Generated by Django 3.2.16 on 2023-01-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_remove_timesheetuser_is_approver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetuser',
            name='approvees',
        ),
        migrations.AddField(
            model_name='timesheetuser',
            name='approvers',
            field=models.ManyToManyField(blank=True, related_name='approvees', to='employee.TimesheetUser'),
        ),
    ]
