# Generated by Django 4.1.6 on 2023-03-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_rename_email_organization_mailer_email'),
        ('employee', '0010_timesheetuser_org_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetuser',
            name='org_manager',
        ),
        migrations.AddField(
            model_name='timesheetuser',
            name='org_manager',
            field=models.ManyToManyField(blank=True, related_name='managers', to='organizations.organization'),
        ),
    ]
