# Generated by Django 4.1.6 on 2023-07-06 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_remove_timesheetuser_org_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=75)),
                ('authentication_code', models.CharField(max_length=8)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.timesheetuser')),
            ],
        ),
    ]
