# Generated by Django 4.1.6 on 2023-07-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_invitee_organization_invitee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitee',
            name='name',
            field=models.CharField(default='Anonymous', max_length=75),
        ),
    ]
