# Generated by Django 4.1.6 on 2023-07-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_invitee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitee',
            name='name',
            field=models.CharField(default='', max_length=75),
        ),
    ]
