# Generated by Django 4.1.6 on 2023-07-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_alter_invitee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitee',
            name='status_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='email',
            field=models.EmailField(max_length=75, unique=True),
        ),
    ]
