# Generated by Django 4.1.6 on 2023-07-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_alter_invitee_authentication_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitee',
            name='wage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
