# Generated by Django 4.1.6 on 2023-07-11 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_invitee_wage'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitee',
            name='inviter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inviter', to='employee.timesheetuser'),
        ),
    ]
