# Generated by Django 4.1.6 on 2023-07-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_invitee_inviter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitee',
            name='email',
            field=models.EmailField(max_length=75),
        ),
    ]
