# Generated by Django 4.1.6 on 2023-07-11 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_rename_email_organization_mailer_email'),
        ('employee', '0020_alter_invitee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitee',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
