# Generated by Django 4.1.6 on 2023-07-11 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_alter_invitee_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitee',
            options={'permissions': (('invite', 'Can invite new user'), ('uninvite', 'Can uninvite an invitee'))},
        ),
    ]
