# Generated by Django 4.1.2 on 2022-10-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('street1', models.CharField(max_length=255)),
                ('street2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=2)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
