# Generated by Django 4.1.2 on 2022-10-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='street2',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
