# Generated by Django 4.1.2 on 2022-10-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_street2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='street2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
