# Generated by Django 3.2.16 on 2022-11-08 00:42

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_auto_20221108_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('seed_date', models.DateTimeField(auto_now=True, help_text='This field is only used if name is weekly or biweekly')),
                ('dates_of_month', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), help_text='Only used with semi-monthly', size=2)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
        migrations.RemoveField(
            model_name='monthlyperiodtype',
            name='organization',
        ),
        migrations.DeleteModel(
            name='BiweeklyPeriodType',
        ),
        migrations.DeleteModel(
            name='MonthlyPeriodType',
        ),
    ]
