# Generated by Django 3.2.16 on 2022-11-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_auto_20221108_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodtype',
            name='seed_date',
            field=models.DateTimeField(help_text='This field is only used if nameweekly or biweekly'),
        ),
    ]
