# Generated by Django 3.2.16 on 2022-11-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_alter_periodtype_seed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodtype',
            name='name',
            field=models.CharField(choices=[('semimonthly', 'SEMI-MONTHLY'), ('monthly', 'MONTHLY'), ('biweekly', 'BI-WEEKLY')], max_length=20),
        ),
    ]
