# Generated by Django 3.2.16 on 2022-11-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_alter_periodtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodtype',
            name='name',
            field=models.CharField(choices=[('semimonthly', 'SEMI-MONTHLY'), ('monthly', 'MONTHLY'), ('biweekly', 'BI-WEEKLY'), ('weekly', 'WEEKLY')], max_length=20),
        ),
    ]
