# Generated by Django 4.1.6 on 2023-03-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_alter_organization_timezone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='email',
            new_name='mailer_email',
        ),
    ]
