# Generated by Django 4.2.6 on 2025-07-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_rename_email_organization_mailer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
