# Generated by Django 4.2.6 on 2025-07-21 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_organization_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='active',
            new_name='hidden',
        ),
    ]
