# Generated by Django 4.1.6 on 2023-10-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('onetime_code', models.CharField(max_length=10)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
