# Generated by Django 4.1.6 on 2023-04-13 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchasing', '0026_remove_part_is_serial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='purchasing.part')),
                ('parent_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_parts', to='inventory.part')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('purchasing.part',),
        ),
        migrations.CreateModel(
            name='InventoryPart',
            fields=[
                ('total_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('inventory.part',),
        ),
    ]
