# Generated by Django 4.1.6 on 2023-04-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialPart',
            fields=[
                ('serial_description', models.CharField(max_length=255, null=True)),
                ('man_serial_number', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('inventory.part',),
        ),
    ]
