# Generated by Django 4.1.6 on 2023-04-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_part_parent_parts_childpart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childpart',
            name='parent_part',
        ),
        migrations.AddField(
            model_name='childpart',
            name='parent_part',
            field=models.ManyToManyField(related_name='child_parts', to='inventory.part'),
        ),
    ]
