# Generated by Django 4.1.6 on 2023-04-16 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_childpart_parent_part_childpart_parent_part'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChildPart',
        ),
    ]
