# Generated by Django 4.1.6 on 2023-04-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_childpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='child_parts',
            field=models.ManyToManyField(blank=True, through='inventory.ChildPart', to='inventory.part'),
        ),
        migrations.AlterField(
            model_name='childpart',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
