# Generated by Django 4.1.6 on 2023-04-18 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_serialpart_equipment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='childpart',
            unique_together={('parent_part', 'child_part')},
        ),
    ]
