# Generated by Django 4.1.6 on 2023-04-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_childpart_unique_together'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='childpart',
            constraint=models.CheckConstraint(check=models.Q(('parent_part', models.F('child_part')), _negated=True), name='not_same'),
        ),
    ]
