# Generated by Django 4.1.6 on 2023-04-18 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_childpart_not_same'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='serialpart_ptr',
        ),
        migrations.DeleteModel(
            name='InventoryPart',
        ),
        migrations.RemoveField(
            model_name='serialpart',
            name='part',
        ),
        migrations.RemoveField(
            model_name='serialpart',
            name='polymorphic_ctype',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='SerialPart',
        ),
    ]
