# Generated by Django 4.1.6 on 2023-04-18 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0013_remove_equipment_serialpart_ptr_delete_inventorypart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_description', models.CharField(max_length=255, null=True)),
                ('man_serial_number', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(choices=[('STANDARD', 'Standard'), ('ASSEMBLY', 'Assembly')], default='STANDARD', max_length=20)),
                ('child_serial_parts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='inventory.serialpart')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.part')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('serialpart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.serialpart')),
                ('equipment_info', models.JSONField(default=dict, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('inventory.serialpart',),
        ),
        migrations.CreateModel(
            name='InventoryPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.part')),
            ],
        ),
    ]
