# Generated by Django 4.1.6 on 2023-04-19 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_serialpart_equipment_inventorypart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serialpart',
            name='child_serial_parts',
        ),
        migrations.AddField(
            model_name='serialpart',
            name='parent_serial_part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serial_children', to='inventory.serialpart'),
        ),
    ]
