# Generated by Django 4.1.6 on 2023-04-19 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_serialpart_parent_serial_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialpart',
            name='parent_serial_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serial_children', to='inventory.serialpart'),
        ),
    ]
