# Generated by Django 4.2.6 on 2024-11-15 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0045_purchaseorder_invoice_purchaseorder_purchase_date'),
        ('inventory', '0019_alter_serialpart_man_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorypart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.part'),
        ),
        migrations.AlterField(
            model_name='inventorypart',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='InventoryMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='purchasing.material')),
            ],
        ),
    ]
