# Generated by Django 4.2.6 on 2024-11-15 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0045_purchaseorder_invoice_purchaseorder_purchase_date'),
        ('inventory', '0020_alter_inventorypart_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.material'),
        ),
        migrations.AlterField(
            model_name='inventorymaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
