# Generated by Django 4.2.6 on 2025-05-16 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('inventory', '0022_location_inventorymaterial_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymaterial',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
        migrations.AlterField(
            model_name='inventorypart',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
