# Generated by Django 4.2.6 on 2025-06-26 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_inventorymaterial_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorymaterial',
            old_name='material',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='inventorypart',
            old_name='part',
            new_name='item',
        ),
    ]
