# Generated by Django 4.2.6 on 2025-07-23 05:43

from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_description'),
        ('purchasing', '0052_food_foodtype'),
        ('inventory', '0024_rename_material_inventorymaterial_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymaterial',
            name='units',
            field=models.CharField(blank=True, default='each', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventorypart',
            name='units',
            field=models.CharField(blank=True, default='each', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='InventoryFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('units', models.CharField(blank=True, default='each', max_length=50, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.food')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
            ],
            options={
                'abstract': False,
            },
            bases=(inventory.models.InventoryItemUniqueMixin, models.Model),
        ),
    ]
