# Generated by Django 4.2.6 on 2026-01-21 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0056_alter_food_options_alter_item_options_and_more'),
        ('locations', '0003_location_full_path'),
        ('employee', '0023_alternatewagecode'),
        ('inventory', '0025_inventorymaterial_units_inventorypart_units_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={},
        ),
        migrations.AlterModelOptions(
            name='serialpart',
            options={},
        ),
        migrations.CreateModel(
            name='InventoryItemTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('ADDITION', 'Addition'), ('SUBTRACTION', 'Subtraction'), ('REMOVAL', 'Removal'), ('USAGE', 'Usage'), ('SOURCE_TRANSFER', 'Source Transfer'), ('DESTINATION_TRANSFER', 'Destination Transfer'), ('UPDATE', 'Update')], max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.timesheetuser')),
            ],
        ),
    ]
