# Generated by Django 4.2.6 on 2026-01-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_alter_equipment_options_alter_part_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitemtransaction',
            name='inventory_item_id',
            field=models.IntegerField(default=0),
        ),
    ]
