# Generated by Django 4.2.6 on 2026-01-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_inventoryitemtransaction_inventory_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitemtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('ADDITION', 'Addition'), ('SUBTRACTION', 'Subtraction'), ('REMOVAL', 'Removal'), ('USAGE', 'Usage'), ('SOURCE_TRANSFER', 'Source Transfer'), ('DESTINATION_TRANSFER', 'Destination Transfer')], max_length=20),
        ),
    ]
