# Generated by Django 4.2.6 on 2026-01-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_alter_inventoryitemtransaction_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitemtransaction',
            name='notes',
        ),
        migrations.AddField(
            model_name='inventoryitemtransaction',
            name='units',
            field=models.CharField(blank=True, default='each', max_length=50, null=True),
        ),
    ]
