# Generated by Django 4.2.6 on 2026-01-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_remove_inventoryitemtransaction_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitemtransaction',
            name='inventory_item_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
