# Generated by Django 4.2.6 on 2026-02-05 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_alter_inventoryitemtransaction_inventory_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitemtransaction',
            name='transfer_transaction_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitemtransaction'),
        ),
    ]
