# Generated by Django 4.2.6 on 2025-01-09 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='documentation',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
