# Generated by Django 4.2.6 on 2025-01-09 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_documentation_content_type_documentation_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentation',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='documentation',
            name='object_id',
        ),
    ]
