# Generated by Django 4.2.6 on 2025-01-09 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0049_remove_item_docs'),
        ('timesheets', '0017_timesheetentry_docs'),
        ('documentation', '0003_remove_documentation_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documentation/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimesheetEntryDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documentation/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheets.timesheetentry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Documentation',
        ),
    ]
