# Generated by Django 4.2.6 on 2025-01-10 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0004_itemdocumentation_timesheetentrydocumentation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemdocumentation',
            old_name='item',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='timesheetentrydocumentation',
            old_name='entry',
            new_name='parent',
        ),
    ]
