# Generated by Django 4.1.6 on 2023-04-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_rename_email_organization_mailer_email'),
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='organization',
            field=models.ManyToManyField(to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='type',
            field=models.CharField(default=('PART', 'Part'), max_length=25),
        ),
        migrations.AddField(
            model_name='vendor',
            name='organization',
            field=models.ManyToManyField(to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='email',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='phone',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
