# Generated by Django 4.1.6 on 2023-04-10 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='part',
            name='item',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='purchase_item',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='purchase_item',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='service',
            name='item',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='item',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='vendororganization',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='vendororganization',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.DeleteModel(
            name='PurchaseHistory',
        ),
        migrations.DeleteModel(
            name='PurchaseItem',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderItem',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.DeleteModel(
            name='VendorOrganization',
        ),
    ]
