# Generated by Django 4.1.6 on 2023-04-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_rename_email_organization_mailer_email'),
        ('purchasing', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='organization',
            field=models.ManyToManyField(through='purchasing.VendorOrganization', to='organizations.organization'),
        ),
    ]
