# Generated by Django 4.1.6 on 2023-04-10 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0010_alter_vendor_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorOrganization',
        ),
    ]
