# Generated by Django 4.1.6 on 2023-04-11 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_rename_email_organization_mailer_email'),
        ('purchasing', '0011_delete_vendororganization'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.JSONField(default=dict, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='purchasing.vendor')),
            ],
        ),
    ]
