# Generated by Django 4.1.6 on 2023-04-11 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_rename_email_organization_mailer_email'),
        ('purchasing', '0012_vendororganization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='organization',
        ),
        migrations.AddField(
            model_name='vendor',
            name='organizations',
            field=models.ManyToManyField(through='purchasing.VendorOrganization', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='vendororganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='vendororganization',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.vendor'),
        ),
    ]
