# Generated by Django 4.1.6 on 2023-04-12 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_rename_email_organization_mailer_email'),
        ('purchasing', '0014_remove_purchaseorderitem_purchase_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Part', max_length=25)),
                ('units', models.CharField(default='Each', max_length=10)),
                ('item', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchasing.item')),
                ('manufacturer', models.ManyToManyField(to='purchasing.manufacturer')),
                ('organization', models.ManyToManyField(to='organizations.organization')),
                ('vendor', models.ManyToManyField(to='purchasing.vendororganization')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.purchaseitem')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_purchase_date', models.DateTimeField(auto_now=True)),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.purchaseorderitem')),
            ],
        ),
    ]
