# Generated by Django 4.1.6 on 2023-04-12 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0015_purchaseitem_purchaseorderitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchasing.item'),
        ),
    ]
