# Generated by Django 4.1.6 on 2023-04-12 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0016_alter_purchaseitem_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendororganization',
            name='contacts',
        ),
    ]
