# Generated by Django 4.1.6 on 2023-04-12 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0017_remove_vendororganization_contacts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
