# Generated by Django 4.1.6 on 2023-04-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0019_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='manufacturer',
            field=models.ManyToManyField(null=True, to='purchasing.manufacturer'),
        ),
    ]
