# Generated by Django 4.1.6 on 2023-04-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0020_alter_purchaseitem_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='term',
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='type',
            field=models.CharField(choices=[('SUBS', 'Subscription'), ('PART', 'Part'), ('SERV', 'Service')], default='PART', max_length=25),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='units',
            field=models.CharField(choices=[('EACH', 'Each'), ('HOUR', 'Hourly'), ('PACK', 'Pack'), ('WEEK', 'Weekly'), ('MONTH', 'Monthly'), ('YEAR', 'Yearly')], default='EACH', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseitem',
            unique_together={('item', 'units')},
        ),
    ]
