# Generated by Django 4.1.6 on 2023-04-12 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_rename_email_organization_mailer_email'),
        ('purchasing', '0022_alter_purchaseitem_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='organization',
        ),
        migrations.AddField(
            model_name='item',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
