# Generated by Django 4.1.6 on 2023-04-12 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchasing', '0024_alter_item_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderitemhistory',
            old_name='last_purchase_date',
            new_name='status_change_date',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='orderer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderer_pos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchaser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaser_pos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved for Ordering'), ('ORDERED', 'Ordered'), ('CLOSED', 'Closed'), ('CANCELED', 'Canceled')], default='CREATED', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='status_change_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='status',
            field=models.CharField(choices=[('ENTERED', 'Entered'), ('ORDERED', 'Ordered'), ('RECEIVED', 'Received')], default='ENTERED', max_length=15),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='status_change_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitemhistory',
            name='status',
            field=models.CharField(default='ENTERED', max_length=15),
        ),
        migrations.CreateModel(
            name='PurchaseOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='CREATED', max_length=20)),
                ('status_change_date', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.purchaseorder')),
            ],
        ),
    ]
