# Generated by Django 4.1.6 on 2023-04-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0026_remove_part_is_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='po',
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='manufacturer',
            field=models.ManyToManyField(to='purchasing.manufacturer'),
        ),
    ]
