# Generated by Django 4.1.6 on 2023-04-28 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0029_alter_vendor_options_vendor_polymorphic_ctype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={},
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='polymorphic_ctype',
        ),
    ]
