# Generated by Django 4.1.6 on 2023-05-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_rename_email_organization_mailer_email'),
        ('purchasing', '0030_alter_vendor_options_remove_vendor_polymorphic_ctype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='notes',
        ),
        migrations.AddField(
            model_name='vendororganization',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='vendororganization',
            unique_together={('vendor', 'organization')},
        ),
    ]
