# Generated by Django 4.1.6 on 2023-05-21 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_rename_email_organization_mailer_email'),
        ('purchasing', '0031_remove_vendor_notes_vendororganization_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='organizations',
        ),
        migrations.AddField(
            model_name='vendor',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.DeleteModel(
            name='VendorOrganization',
        ),
    ]
