# Generated by Django 4.1.6 on 2023-05-21 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_rename_email_organization_mailer_email'),
        ('purchasing', '0032_remove_vendor_organizations_vendor_organization_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendor',
            unique_together={('name', 'organization')},
        ),
    ]
