# Generated by Django 4.2.6 on 2024-07-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0037_paymentaccount_alter_purchaseorder_status_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='last_four',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
