# Generated by Django 4.2.6 on 2024-09-18 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0038_alter_paymentaccount_last_four'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='purchasing.item')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('purchasing.item',),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='type',
            field=models.CharField(choices=[('SUBS', 'Subscription'), ('PART', 'Part'), ('SERV', 'Service'), ('MATERIAL', 'Material')], default='PART', max_length=25),
        ),
    ]
