# Generated by Django 4.2.6 on 2024-09-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0039_material_alter_purchaseitem_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
