# Generated by Django 4.2.6 on 2024-09-19 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0040_vendortype'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.vendortype'),
        ),
    ]
