# Generated by Django 4.2.6 on 2024-10-03 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import purchasing.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchasing', '0041_vendor_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=75, unique=True)),
                ('type_description', models.CharField(max_length=255)),
                ('details_list', models.JSONField(default=purchasing.models.default_itemtype_data)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=75, unique=True)),
                ('type_description', models.CharField(max_length=255)),
                ('details_list', models.JSONField(default=purchasing.models.default_itemtype_data)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=75, unique=True)),
                ('type_description', models.CharField(max_length=255)),
                ('details_list', models.JSONField(default=purchasing.models.default_itemtype_data)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=75, unique=True)),
                ('type_description', models.CharField(max_length=255)),
                ('details_list', models.JSONField(default=purchasing.models.default_itemtype_data)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='material',
            name='details',
            field=models.JSONField(default=purchasing.models.default_itemdetails_data),
        ),
        migrations.AddField(
            model_name='part',
            name='details',
            field=models.JSONField(default=purchasing.models.default_itemdetails_data),
        ),
        migrations.AddField(
            model_name='service',
            name='details',
            field=models.JSONField(default=purchasing.models.default_itemdetails_data),
        ),
        migrations.AddField(
            model_name='subscription',
            name='details',
            field=models.JSONField(default=purchasing.models.default_itemdetails_data),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchaser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaser_pos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='material',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.materialtype'),
        ),
        migrations.AddField(
            model_name='part',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.parttype'),
        ),
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.servicetype'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.subscriptiontype'),
        ),
    ]
