# Generated by Django 4.2.6 on 2024-10-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0042_materialtype_parttype_servicetype_subscriptiontype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='manufacturer',
            field=models.ManyToManyField(blank=True, null=True, to='purchasing.manufacturer'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='vendor',
            field=models.ManyToManyField(blank=True, null=True, to='purchasing.vendor'),
        ),
    ]
