# Generated by Django 4.2.6 on 2024-11-06 07:05

from django.db import migrations, models
import django.db.models.deletion
import purchasing.models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0043_alter_purchaseitem_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseitem',
            unique_together={('item', 'units', 'type')},
        ),
        migrations.AlterField(
            model_name='material',
            name='details',
            field=models.JSONField(blank=True, default=purchasing.models.default_itemdetails_data),
        ),
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.materialtype'),
        ),
        migrations.AlterField(
            model_name='part',
            name='details',
            field=models.JSONField(blank=True, default=purchasing.models.default_itemdetails_data),
        ),
        migrations.AlterField(
            model_name='part',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.parttype'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='manufacturer',
            field=models.ManyToManyField(blank=True, to='purchasing.manufacturer'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='vendor',
            field=models.ManyToManyField(blank=True, to='purchasing.vendor'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='details',
            field=models.JSONField(blank=True, default=purchasing.models.default_itemdetails_data),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.servicetype'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='details',
            field=models.JSONField(blank=True, default=purchasing.models.default_itemdetails_data),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.subscriptiontype'),
        ),
    ]
