# Generated by Django 4.2.6 on 2024-11-07 05:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0044_alter_purchaseitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
