# Generated by Django 4.2.6 on 2024-12-18 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
        ('projects', '0007_rename_doc_description_projectdocumentation_description'),
        ('purchasing', '0046_purchaseorder_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='documentation',
            field=models.ManyToManyField(blank=True, null=True, to='documentation.documentation'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
    ]
