# Generated by Django 4.2.6 on 2024-12-11 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_finished_date'),
        ('purchasing', '0046_purchaseorder_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
    ]
