# Generated by Django 4.2.6 on 2024-12-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
        ('purchasing', '0047_item_documentation_alter_purchaseorder_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='documentation',
        ),
        migrations.AddField(
            model_name='item',
            name='docs',
            field=models.ManyToManyField(blank=True, to='documentation.documentation'),
        ),
    ]
