# Generated by Django 4.2.6 on 2025-01-09 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0048_remove_item_documentation_item_docs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='docs',
        ),
    ]
