# Generated by Django 4.2.6 on 2025-01-11 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0047_alter_purchaseorder_project'),
        ('purchasing', '0049_remove_item_docs'),
    ]

    operations = [
    ]
