# Generated by Django 4.2.6 on 2025-07-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0050_merge_20250111_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='discount_coupon',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
