# Generated by Django 4.2.6 on 2025-07-23 05:31

from django.db import migrations, models
import django.db.models.deletion
import purchasing.models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0051_purchaseorder_discount_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='purchasing.item')),
                ('details', models.JSONField(blank=True, default=purchasing.models.default_itemdetails_data)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('purchasing.item',),
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=75, unique=True)),
                ('type_description', models.CharField(max_length=255)),
                ('details_list', models.JSONField(default=purchasing.models.default_itemtype_data)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
