# Generated by Django 4.2.6 on 2025-07-23 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0052_food_foodtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.foodtype'),
        ),
    ]
