# Generated by Django 4.2.6 on 2025-07-29 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0053_food_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.paymentaccount'),
        ),
    ]
