# Generated by Django 4.2.6 on 2025-07-29 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0054_purchaseorder_payment_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.paymentaccount'),
        ),
    ]
