# Generated by Django 4.2.6 on 2026-01-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0055_alter_purchaseorder_payment_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
    ]
