# Generated by Django 3.2.16 on 2022-11-04 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_street2'),
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesheetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('period_in_year', models.IntegerField()),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
    ]
