# Generated by Django 3.2.16 on 2022-11-05 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_monthlyperiodtype_semimonthlyperiodtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyPeriodType',
        ),
        migrations.DeleteModel(
            name='SemiMonthlyPeriodType',
        ),
    ]
