# Generated by Django 3.2.16 on 2022-11-21 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_auto_20221105_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetperiod',
            name='period_in_year',
        ),
    ]
