# Generated by Django 3.2.16 on 2022-11-22 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_alter_organization_timezone'),
        ('timesheets', '0005_remove_timesheetperiod_period_in_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timesheetperiod',
            unique_together={('org', 'date_start', 'date_end')},
        ),
    ]
