# Generated by Django 3.2.16 on 2022-11-22 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0006_alter_timesheetperiod_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetentry',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timesheets.timesheetperiod'),
        ),
    ]
