# Generated by Django 3.2.16 on 2022-11-23 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_alter_organization_timezone'),
        ('timesheets', '0007_timesheetentry_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetperiod',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
