# Generated by Django 3.2.16 on 2022-11-24 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_alter_organization_timezone'),
        ('timesheets', '0008_alter_timesheetperiod_org'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timesheetperiod',
            unique_together={('org_id', 'date_start', 'date_end')},
        ),
    ]
