# Generated by Django 3.2.16 on 2022-12-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0009_alter_timesheetperiod_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetentry',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
