# Generated by Django 3.2.16 on 2022-12-31 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0010_timesheetentry_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheetentry',
            options={'permissions': (('approve_timesheetentry', 'can approve timesheetentry'),)},
        ),
    ]
