# Generated by Django 3.2.16 on 2022-12-31 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0011_alter_timesheetentry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheetperiod',
            options={'permissions': (('approve_timesheetperiod', 'can approve timesheetperiod'),)},
        ),
    ]
