# Generated by Django 3.2.16 on 2023-01-21 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_timesheetuser_phone'),
        ('timesheets', '0012_alter_timesheetperiod_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTimesheetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('date_approved', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheets.timesheetperiod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.timesheetuser')),
            ],
            options={
                'unique_together': {('user', 'period')},
            },
        ),
    ]
