# Generated by Django 3.2.16 on 2023-01-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0013_usertimesheetperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimesheetperiod',
            name='date_approved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usertimesheetperiod',
            name='date_submitted',
            field=models.DateTimeField(null=True),
        ),
    ]
