# Generated by Django 4.1.6 on 2023-03-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0014_auto_20230122_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetentry',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
