# Generated by Django 4.2.6 on 2024-07-17 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_finished_date'),
        ('timesheets', '0015_timesheetentry_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetentry',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
    ]
