# Generated by Django 4.2.6 on 2024-11-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0016_timesheetentry_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetentry',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to='documentation/'),
        ),
    ]
