# Generated by Django 4.2.6 on 2025-05-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
