# Generated by Django 4.2.6 on 2025-09-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='full_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
