# Generated by Django 4.2.6 on 2025-11-12 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0007_rename_doc_description_projectdocumentation_description'),
        ('employee', '0023_alternatewagecode'),
        ('inventory', '0025_inventorymaterial_units_inventorypart_units_and_more'),
        ('timesheets', '0017_timesheetentry_docs'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('STARTED', 'Started'), ('COMPLETED', 'Completed'), ('APPROVED', 'Approved'), ('CLOSED', 'Closed'), ('SCRAPPED', 'Scrapped')], default='CREATED', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assignees', to='employee.timesheetuser')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creators', to='employee.timesheetuser')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.equipment')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='WorkEntry',
            fields=[
                ('timesheetentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timesheets.timesheetentry')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorders.workorder')),
            ],
            bases=('timesheets.timesheetentry',),
        ),
    ]
