# Generated by Django 4.2.6 on 2024-07-24 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_mileage_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileage',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.rate'),
        ),
    ]
