# Generated by Django 4.2.6 on 2024-07-25 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_expense_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mileage',
            name='accrue_date',
        ),
        migrations.AddField(
            model_name='expense',
            name='accrue_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 25, 5, 35, 14, 427802)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('MILEAGE', 'Mileage'), ('MEALS', 'Meals'), ('TRANSPORTATION', 'Transportation'), ('LODGING', 'Lodging'), ('MISC', 'Miscellaneous')], default='MISC', max_length=20),
        ),
    ]
