# Generated by Django 4.2.6 on 2024-08-02 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_remove_mileage_accrue_date_expense_accrue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='accrue_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 2, 14, 40, 50, 192555)),
        ),
    ]
