# Generated by Django 4.2.6 on 2024-08-07 13:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_alternatewagecode'),
        ('timesheets', '0016_timesheetentry_project'),
        ('projects', '0003_alter_project_finished_date'),
        ('accounting', '0012_alter_expense_accrue_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mileage',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='mileage',
            name='project',
        ),
        migrations.AddField(
            model_name='expense',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timesheets.timesheetentry'),
        ),
        migrations.AddField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.timesheetuser'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='accrue_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 7, 13, 32, 0, 334380)),
        ),
    ]
