# Generated by Django 4.2.6 on 2024-08-18 06:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_remove_mileage_entry_remove_mileage_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lodging',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.expense')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nights', models.IntegerField(default=1)),
            ],
            bases=('accounting.expense',),
        ),
        migrations.AlterField(
            model_name='expense',
            name='accrue_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 18, 6, 4, 6, 992264)),
        ),
    ]
