# Generated by Django 4.2.6 on 2024-08-18 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_lodging_alter_expense_accrue_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lodging',
            old_name='rate',
            new_name='nightly_rate',
        ),
        migrations.AlterField(
            model_name='expense',
            name='accrue_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 18, 6, 12, 33, 744206)),
        ),
    ]
