# Generated by Django 4.2.6 on 2024-08-20 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_rename_rate_lodging_nightly_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='accrue_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 20, 7, 36, 32, 714872)),
        ),
    ]
