# Generated by Django 4.2.6 on 2024-09-18 07:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0039_material_alter_purchaseitem_type'),
        ('accounting', '0016_alter_expense_accrue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lodging',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.vendor'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='accrue_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 18, 7, 6, 25, 785498)),
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.expense')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.vendor')),
            ],
            bases=('accounting.expense',),
        ),
    ]
