# Generated by Django 4.2.6 on 2024-09-18 07:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_expense_description_lodging_vendor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.expense')),
                ('meal_type', models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('GROCERIES', 'Groceries')], max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tip', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('receipt', models.URLField(null=True)),
            ],
            bases=('accounting.expense',),
        ),
        migrations.AddField(
            model_name='lodging',
            name='receipt',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='transportation',
            name='receipt',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='transportation',
            name='transportation_type',
            field=models.CharField(choices=[('BUS', 'Bus'), ('AIR', 'Airfare'), ('TAXI', 'Taxi'), ('RIDE', 'Rideshare')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='accrue_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 18, 7, 22, 0, 88614)),
        ),
    ]
