# Generated by Django 4.2.6 on 2024-09-19 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_meals_lodging_receipt_transportation_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='accrue_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 19, 5, 7, 51, 867619)),
        ),
    ]
