# Generated by Django 4.2.6 on 2024-09-19 18:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0041_vendor_type'),
        ('accounting', '0019_alter_expense_accrue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.vendor'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='accrue_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 19, 18, 16, 50, 276936)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('MILEAGE', 'Mileage'), ('MEALS', 'Meals'), ('TRANSPORTATION', 'Transportation'), ('LODGING', 'Lodging'), ('MISC', 'Misc')], default='MISC', max_length=20),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='receipt',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='meal_type',
            field=models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('GROCERIES', 'Groceries')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='receipt',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='receipt',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Misc',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.expense')),
                ('receipt', models.URLField(blank=True, null=True)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.vendor')),
            ],
            bases=('accounting.expense',),
        ),
    ]
