# Generated by Django 4.2.6 on 2024-09-19 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_meals_vendor_alter_expense_accrue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='accrue_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 19, 18, 23, 43, 460819)),
        ),
    ]
