# Generated by Django 4.2.6 on 2024-09-20 06:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0041_vendor_type'),
        ('accounting', '0022_alter_expense_accrue_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodging',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='lodging',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='misc',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='misc',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='expense',
            name='accrue_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 20, 6, 56, 24, 22268)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('MILEAGE', 'Mileage'), ('MEALS', 'Meals'), ('TRANSPORTATION', 'Transportation'), ('LODGING', 'Lodging'), ('SERVICE', 'Service'), ('MISC', 'Misc')], default='MISC', max_length=20),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='transportation_type',
            field=models.CharField(choices=[('BUS', 'Bus'), ('AIR', 'Airfare'), ('TAXI', 'Taxi'), ('RIDE', 'Rideshare'), ('TRAIN', 'Train')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ServiceExpense',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.expense')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.service')),
            ],
            bases=('accounting.expense',),
        ),
    ]
