# Generated by Django 4.2.6 on 2024-09-20 06:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0041_vendor_type'),
        ('accounting', '0023_remove_lodging_receipt_remove_lodging_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='accrue_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 20, 6, 57, 17, 156842)),
        ),
        migrations.CreateModel(
            name='VendorExpense',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.expense')),
                ('receipt', models.URLField(blank=True, null=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.paymentaccount')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.vendor')),
            ],
            bases=('accounting.expense',),
        ),
    ]
