# Generated by Django 4.2.6 on 2024-09-20 07:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0041_vendor_type'),
        ('accounting', '0025_remove_meals_expense_ptr_remove_misc_expense_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lodging',
            fields=[
                ('vendorexpense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.vendorexpense')),
                ('nightly_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nights', models.IntegerField(default=1)),
            ],
            bases=('accounting.vendorexpense',),
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.expense')),
                ('meal_type', models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('GROCERIES', 'Groceries')], max_length=20, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tip', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            bases=('accounting.expense',),
        ),
        migrations.CreateModel(
            name='Misc',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.expense')),
            ],
            bases=('accounting.expense',),
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.expense')),
                ('transportation_type', models.CharField(choices=[('BUS', 'Bus'), ('AIR', 'Airfare'), ('TAXI', 'Taxi'), ('RIDE', 'Rideshare'), ('TRAIN', 'Train')], max_length=10, null=True)),
            ],
            bases=('accounting.expense',),
        ),
        migrations.AlterField(
            model_name='expense',
            name='accrue_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 20, 7, 17, 23, 152819)),
        ),
        migrations.CreateModel(
            name='ServiceExpense',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.expense')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.service')),
            ],
            bases=('accounting.expense',),
        ),
    ]
