# Generated by Django 4.2.6 on 2024-09-20 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_lodging_meals_misc_transportation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='accrue_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 20, 7, 30, 18, 308607)),
        ),
    ]
