# Generated by Django 4.2.6 on 2024-09-20 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_alter_expense_accrue_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals',
            name='expense_ptr',
        ),
        migrations.RemoveField(
            model_name='misc',
            name='expense_ptr',
        ),
        migrations.RemoveField(
            model_name='serviceexpense',
            name='expense_ptr',
        ),
        migrations.RemoveField(
            model_name='serviceexpense',
            name='service',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='expense_ptr',
        ),
        migrations.AlterField(
            model_name='expense',
            name='accrue_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 20, 7, 33, 19, 955306)),
        ),
        migrations.DeleteModel(
            name='Lodging',
        ),
        migrations.DeleteModel(
            name='Meals',
        ),
        migrations.DeleteModel(
            name='Misc',
        ),
        migrations.DeleteModel(
            name='ServiceExpense',
        ),
        migrations.DeleteModel(
            name='Transportation',
        ),
    ]
