# Generated by Django 4.2.6 on 2024-09-20 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0041_vendor_type'),
        ('accounting', '0029_lodging_meals_misc_transportation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceExpense',
            new_name='Service',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service',
            new_name='serv',
        ),
        migrations.AlterField(
            model_name='expense',
            name='accrue_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 20, 8, 39, 37, 975700)),
        ),
    ]
