# Generated by Django 4.2.6 on 2024-12-11 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_rename_serviceexpense_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='accrue_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 11, 5, 40, 14, 543630)),
        ),
    ]
