# Generated by Django 4.2.6 on 2024-12-11 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_alter_expense_accrue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='accrue_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 11, 5, 41, 33, 823147)),
        ),
    ]
