# Generated by Django 4.2.6 on 2024-12-11 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_alter_expense_accrue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='accrue_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 11, 6, 6, 12, 625617)),
        ),
    ]
